name: 'Initial Deploy Action'

description: >
  🪂  Initial action to deploy

branding:
  icon: 'command'
  color: 'red'

inputs:
  actor:
    description: 'The deploy actor'
    required: true
  token:
    description: 'The deploy token'
    required: true
  base:
    description: 'The path to .github folder'
    required: true
  tmp:
    description: 'The temporary path'
    required: true

runs:
  using: composite
  steps:
    - name: 💎 Get the latest commit message
      id: commit
      shell: bash
      run: |
        git config --global user.name "${{ inputs.actor }}"
        git config --global user.email "${{ inputs.actor }}@users.noreply.github.com"

        git config --global core.autocrlf false
        git config --global --add safe.directory "${{ github.workspace }}"       
       
        echo 'LATEST_COMMIT='$(curl -s "https://api.github.com/users/eq19/events/public" | jq ".[0].payload.commits[0].message") >> ${GITHUB_ENV}

    - name: 💎 Update workflow conveniently
      id: update
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          BASE="D:/a/_actions/eq19/eq19/v1/.github"
        else
          BASE=/home/runner/work/_actions/eq19/eq19/v1/.github 
          REMOTE_REPO="https://${{ inputs.actor }}:${{ inputs.token }}@github.com/${{ github.repository }}.git"

          cd "${{ github.workspace }}" && rm -rf .github
          cp -r "$BASE" . && chown -R "$(whoami)" .github

          git remote set-url origin $REMOTE_REPO        
          git add . && git commit -m ${{ env.LATEST_COMMIT }} && git push

          if [ $? -eq 0 ]; then exit 1; fi
        fi

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        allow-prereleases: true

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip -q install --upgrade pip setuptools six wheel
        python -m pip -q install -r ${{ inputs.action_path }}/requirements-dev.txt
        $BASE/entrypoint/init.sh

    - name: View context attributes
      uses: actions/github-script@v7
      with:
        script: console.log(context)
