name: Build devcontainer
description: Build a devcontainer that is compliant with the spec

branding:
  icon: "activity"
  color: "green"

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  image_name:
    description: "Name for the container to be created. Example: nginx"
    required: true
  image_tag:
    description: Tag to use for the new image
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  build_args:
    description: Build args
    required: false
    default: ""
  devcontainer_subfolder:
    description: |
      The path where the action will look for the `.devcontainer` folder.
    required: false
  devcontainer_run_cmd_path:
    description: |
      Path to a script file to run inside the devcontainer once the build is 
      complete. You can run some checks using this feature
    required: false
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_token }}

    - name: Variables
      shell: bash
      id: variables
      run: |
        repo_name=${{ inputs.docker_hub_username }}/${{ inputs.image_name }}
        image_tag=${{ inputs.image_tag }}
        dev_image_tag="$image_tag"
        repo_ref="$repo_name:$image_tag"
        image_ref="${{ inputs.image_name }}:$image_tag"
        dev_repo_ref="$repo_name:$dev_image_tag"
        dev_image_ref="${{ inputs.image_name }}:$dev_image_tag"

        echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
        echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
        echo "dev_image_tag=$dev_image_tag" >> $GITHUB_OUTPUT
        echo "repo_ref=$repo_ref" >> $GITHUB_OUTPUT
        echo "image_ref=$image_ref" >> $GITHUB_OUTPUT
        echo "dev_repo_ref=$dev_repo_ref" >> $GITHUB_OUTPUT
        echo "dev_image_ref=$dev_image_ref" >> $GITHUB_OUTPUT

    - name: Pre-build image and run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ${{ steps.variables.outputs.repo_name }}
        cacheFrom: ${{ steps.variables.outputs.repo_name }}
        imageTag: ${{ steps.variables.outputs.image_tag }}
        subFolder: ${{ inputs.devcontainer_subfolder }}
        skipContainerUserIdUpdate: true
        runCmd: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        push: always
    
    - name: Set Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_token }}
        repository: ${{ steps.variables.outputs.repo_name }}
        short-description: ${{ inputs.docker_hub_repo_short_description }}
        readme-filepath: ${{ inputs.docker_hub_repo_readme_file_path }}
