[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:root

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:postgres]
command=docker-entrypoint.sh postgres
autostart=true
autorestart=true

[program:freqtrade_dry]
command=freqtrade trade -v --userdir /home/runner/data_dry --log-file /var/log/apt/freqtrade_dry.log
autostart=false
autorestart=true

[program:freqtrade_live]
command=freqtrade trade -v --userdir /home/runner/data_live --log-file /var/log/apt/freqtrade_live.log
autostart=false
autorestart=true

[program:monitor_freqtrade]
command=/freqtrade.sh
autostart=false
autorestart=true
