[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:root

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface


[program:postgres]
command=docker-entrypoint.sh postgres
autostart=false
autorestart=false


[program:freqtrade_live]
command=/home/runner/data_live/ft_client/test_client/supervisor.sh
environment=RUN_MODE="live",DATA_DIR="/home/runner/data_live",CONFIG_FILE="/home/runner/data_live/config.json",EXCHANGE_CONFIG="/home/runner/data_live/config_examples/config_exchange.example.json",FREQAI_MODEL="FREQAIMODEL_LIVE"
autostart=false
autorestart=true


[program:freqtrade_dry]
command=/home/runner/data_dry/ft_client/test_client/supervisor.sh
environment=RUN_MODE="dry",DATA_DIR="/home/runner/data_dry",CONFIG_FILE="/home/runner/data_dry/config.json",EXCHANGE_CONFIG="/home/runner/data_dry/config_examples/config_exchange.example.json",FREQAI_MODEL="FREQAIMODEL_DRY"
autostart=false
autorestart=true


[program:monitor_freqtrade]
command=/freqtrade.sh
autostart=false
autorestart=true
