[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:root

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:postgres]
command=docker-entrypoint.sh postgres
autostart=false
autorestart=false

[program:freqtrade_dry]
command=freqtrade trade -v --userdir /home/runner/data_dry --log-file /home/runner/data_dry/logs/freqtrade.log --freqaimodel FREQAIMODEL_DRY
autostart=false
autorestart=true

[program:freqtrade_live]
command=freqtrade trade -v --userdir /home/runner/data_live --log-file /home/runner/data_live/logs/freqtrade.log --freqaimodel FREQAIMODEL_LIVE
autostart=false
autorestart=true

[program:monitor_freqtrade]
command=/freqtrade.sh
autostart=false
autorestart=true
