[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:root

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:postgres]
command=docker-entrypoint.sh postgres
autostart=true
autorestart=true

[program:freqtrade]
command=freqtrade trade
autostart=false
autorestart=false
