[supervisord]
nodaemon=true

[program:freqtrade]
command=freqtrade trade
autostart=false  # Do not start automatically
autorestart=false  # Prevent auto-restart by Supervisor

[program:postgres]
command=docker-entrypoint.sh postgres
autostart=true
autorestart=true

[program:freqtrade_start]
command=/start_freqtrade.sh
autostart=true
autorestart=true
