[supervisord]
nodaemon=true

[program:postgres]
command=docker-entrypoint.sh postgres
autostart=true
autorestart=true

[program:freqtrade_start]
command=/start_freqtrade.sh
autostart=true
autorestart=true
